title: Ori Mizrahi # your name (or website title) here
logo: "/images/o.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Currently studying Computer Science at UC Santa Barbara
  <br><br>
  Here are a some of my favorite projects
  <br><br>
  <a href="https://www.linkedin.com/in/ori-mizrahi-146161154/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
